version: "3.9"
services:
  foundation-server:
    build:
      context: ./foundation-server
    restart: always
    depends_on: 
      bitcoin:
        condition: service_healthy
    environment:
      - TBTC_ADDRESS=tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw
    volumes:
      - ./foundation-server/configs:/foundation-server/configs/
    network_mode: host
    # ports:
    #   - '3002:3002'
    #   - '3001:3001'
  redis:
    restart: always
    image: redis:alpine
    network_mode: host
    volumes: 
      - ./redis-cache:/data
    # expose:
    #   - '6379'
    # ports:
    #   - '6379:6379'
  bitcoin:
    image: ruimarinho/bitcoin-core:22.0
    restart: always
    volumes:
      - ./bitcoin-testnet-data:/home/bitcoin/.bitcoin
    command:
      -printtoconsole
      -testnet=1
      -server
      -maxconnections=250
      -rpcuser=rpcuser
      -rpcpassword=rpcpassword
      -rpcbind=127.0.0.1
      -deprecatedrpc=accounts
      -rpcport=18332
    network_mode: host
    healthcheck:
      test: curl -f --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getblockchaininfo","params":[]}' -H 'content-type:text/plain;' http://rpcuser:rpcpassword@127.0.0.1:18332 || exit 1
      interval: 5s
      timeout: 30s
      retries: 99999999
    # expose:
    #   - '18332'
    #   - '18333'
    # ports:
    #  - '18332:18332'
    #  - '18333:18333'
