version: "3.9"
services:
  foundation-server:
    depends_on:
      - bitcoin
    build:
      context: ./foundation-server
    restart: always
    environment:
      - TBTC_ADDRESS=tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw
    volumes:
      - ./foundation-server/configs:/foundation-server/configs/
    ports:
      - '3002:3002'
      - '3001:3001'
  redis:
    depends_on:
      - bitcoin
    image: redis:alpine
    expose:
      - '6379'
    # ports:
    #   - '6379:6379'
  bitcoin:
    image: ruimarinho/bitcoin-core:22.0
    restart: always
    depends_on:
      bootstrap-chaindata:
        condition: service_completed_successfully
    volumes:
      - ./bitcoin-testnet-data:/home/bitcoin/.bitcoin
    command:
      -printtoconsole
      -testnet=1
      -server
      -maxconnections=250
      -rpcuser=rpcuser
      -rpcpassword=rpcpassword
      -rpcallowip=10.211.0.0/16
      -rpcallowip=172.17.0.0/16
      -rpcallowip=192.168.0.0/16
      -deprecatedrpc=accounts
      -rpcport=18332
    expose:
      - '18332'
      - '18333'
    # ports:
    #  - '18332:18332'
    #  - '18333:18333'
  bootstrap-chaindata:
    image: ubuntu:20.04
    volumes:
      - ./bitcoin-testnet-data/testnet3:/chaindata
    working_dir: /chaindata
    command: >
        bash -c "
        [ $(ls -A .) ] || exit 0
        && apt-get update -qq
        && apt-get install -y -q curl zstd
        && curl -s -f https://m-shared-public.s3.eu-central-1.amazonaws.com/bitcoin-testnet-chain.tar.zst | tar --use-compress-program=unzstd -xvf -"
