version: "3.9"
services:
  foundation-server:
    build:
      context: ./foundation-server
    restart: always
    environment:
      - TBTC_ADDRESS=tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw
    volumes:
      - ./foundation-server/configs:/foundation-server/configs/
    ports:
      - '3002:3002'
      - '3001:3001'
  redis:
    image: redis:alpine
    expose:
      - '6379'
    # ports:
    #   - '6379:6379'
  bitcoin:
    image: ruimarinho/bitcoin-core:22.0
    restart: always
    volumes:
      - ./bitcoin-testnet-data:/home/bitcoin/.bitcoin
    command:
      -printtoconsole
      -testnet=1
      -server
      -maxconnections=250
      -rpcuser=rpcuser
      -rpcpassword=rpcpassword
      -rpcallowip=10.211.0.0/16
      -rpcallowip=172.17.0.0/16
      -rpcallowip=192.168.0.0/16
      -deprecatedrpc=accounts
      -rpcport=18332
    expose:
      - '18332'
      - '18333'
    # ports:
    #  - '18332:18332'
    #  - '18333:18333'
